// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-ui/lib/button')['default']
    ElColorPicker: typeof import('element-ui/lib/color-picker')['default']
    ElProgress: typeof import('element-ui/lib/progress')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}

export { }
